### ISSUE TITLE
Max lines display?

### ISSUE THREAD

**Issue by rwbc** [fohristiwhirl/nibbler#55]
After updating from 0.53 to 1.01 rc2 and now 1.02 it seems the previous option for controlling the displayed max number of analysis lines does not work anymore. (pasted from old config to new config)

It seems there is no option anymore for this at all. Also just using 'Top move only' seems not work here. Is there another way to change the display from 20 max lines?

**Comment by fohristiwhirl** [comment]
No, at some point I added a scroll bar so it could accomodate any number. There didn't seem any good reason to have the limit any more.

**Comment by fohristiwhirl** [comment]
Alright I've added it back to the repo. Since there might not be a new prebuilt release for a while, you may want to do the following:

* Download the repo with the green "clone or download" button.
* Find the folder `resources/app` in your Nibbler installation.
* Replace everything there with the current files, especially `80_info.js` and `modules/config_io.js`

**Comment by rwbc** [comment]
Thanks!

**Comment by fohristiwhirl** [comment]
Still curious why this is a good thing to have?

**Comment by rwbc** [comment]
Normally we don't want to look at 20 analysis lines when we know just X-Y moves are the important ones and the other ones are just junk.

BTW can the arrows also be limited to the desired number to be consistent?

**Comment by fohristiwhirl** [comment]
That's a lot more troublesome to do - say you've limited it to 4 lines of analysis, there's no guarantee that you would get the very same arrows, because analysis lines are sorted by nodes / visits whereas arrow choice is based on the U statistic.

So I'd have to think about it... I'm fairly unlikely to implement this.

**Comment by rwbc** [comment]
Don't worry that is not too important and I can still stick to just show the top one.
